name: CI/CD Pipeline

on:
  push:
    branches: [ "develop", "feature-kubernetes" ] # Se d√©clenche sur ces branches

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Producer
        uses: docker/build-push-action@v4
        with:
          context: ./producer
          push: true
          tags: TON_USER_DOCKERHUB/kafka-producer:latest

      - name: Build and push Consumer
        uses: docker/build-push-action@v4
        with:
          context: ./consumer
          push: true
          tags: lovecookie93/kafka-consumer:latest